const RECOMMENDATION_EXPIRY_MS = 30 * 60 * 1000;
const SESSION_TRIGGER_LOCK_TTL_SECONDS = 300;
const EXAM_REMINDER_DEDUPE_TTL_SECONDS = 36 * 60 * 60;
const PUBLIC_PREEXAM_QUIZ_DEDUPE_TTL_SECONDS = 7 * 24 * 60 * 60;
const PUBLIC_PREEXAM_QUIZ_OFFSETS_DAYS = 3;

const HANDLER_CONSTANTS = {
  RECOMMENDATION_EXPIRY_MS,
  SESSION_TRIGGER_LOCK_TTL_SECONDS,
  EXAM_REMINDER_DEDUPE_TTL_SECONDS,
  PUBLIC_PREEXAM_QUIZ_DEDUPE_TTL_SECONDS,
  PUBLIC_PREEXAM_QUIZ_OFFSETS_DAYS,
};

export default HANDLER_CONSTANTS;
