import { ENV } from "./env";

export * from "./constants";
export * from "./logger";
export * from "./redis";
export * from "./bullboard";
export * from "./multer";
export * from "./mail";

export const CONFIG = {
  PORT: ENV.PORT,
  DATABASE: { MONGO_URI: ENV.MONGO_URI },
  ENV: ENV.NODE_ENV,
  ACCESS_TOKEN_SECRET: ENV.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: ENV.REFRESH_TOKEN_SECRET,
  SALT_ROUNDS: ENV.SALT_ROUNDS,
  LOGS: ENV.LOGS,
  SOCKET_PATH: ENV.SOCKET_PATH,
  PAYSTACK_SECRET_KEY_TEST: ENV.PAYSTACK_SECRET_KEY_TEST,
  PAYSTACK_SECRET_KEY_LIVE: ENV.PAYSTACK_SECRET_KEY_LIVE,
  GOOGLE: ENV.GOOGLE,
  GITHUB: ENV.GITHUB,
  SMTP: ENV.SMTP,
  VAPID: ENV.VAPID,
  FRONTEND_URL: ENV.FRONTEND_URL,
  REDIS_URL: ENV.REDIS_URL,
  BULL_BOARD: ENV.BULL_BOARD,
  AI: ENV.AI,
  GROQ: ENV.GROQ,
  OPENROUTER: ENV.OPENROUTER,
  CLOUDINARY: ENV.CLOUDINARY,
};