import { Document, Types } from "mongoose";
import { IUpload } from "@/system";
import { PlanTier, PlanDuration } from "@/subscriptions";

export interface IEmailUpdate extends Document {
  subject: string;
  /** Markdown content — the canonical source for both plain-text and HTML rendering. */
  content: string;
  /** Rendered HTML derived from `content` (populated when the draft is created/updated). */
  renderedHtml?: string;
  context?: string;
  type: "update" | "promotional" | "security" | "general";
  links?: { label: string; url: string }[];
  status: "draft" | "approved" | "sent" | "rejected";
  /** True when the content was generated by the AI rather than manually authored. */
  isAiGenerated: boolean;
  /**
   * Entity reference strings that were resolved during AI generation.
   * Format: "/<collection>/<id>", e.g. "/institutions/64abc123".
   * Useful for auditing what data fed the generation.
   */
  aiContextRefs?: string[];
  /** User who requested the AI generation (or manual creator). */
  requestedBy?: Types.ObjectId;
  /** Admin/moderator who approved the draft for sending. */
  approvedBy?: Types.ObjectId;
  approvedAt?: Date;
  /** Admin/moderator who rejected the draft. */
  rejectedBy?: Types.ObjectId;
  rejectedAt?: Date;
  rejectionReason?: string;
  sentAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}
export type PlatformRole = "super_admin" | "creator" | "moderator" | "student";

export type Permission =
  | "platform:manage_super_admins"

  // Settings
  | "settings:read"
  | "settings:write"

  // Members / role assignment
  | "role:read"
  | "role:invite"
  | "role:remove"
  | "role:assign_role"

  // Content lifecycle
  | "content:read"
  | "content:create"
  | "content:edit"
  | "content:delete"
  | "content:submit_for_approval"
  | "content:approve"
  | "content:publish"
  | "content:archive"

  // Sharing policies
  | "sharing:read"
  | "sharing:write"

  // Subscription-based personal features
  | "personal:flashcards"
  | "personal:quizzes"
  | "personal:ai"
  | "personal:progress";

export const ROLE_PERMISSIONS: Record<PlatformRole, Permission[]> = {
  super_admin: [
    "platform:manage_super_admins",
    "settings:read",
    "settings:write",
    "role:read",
    "role:invite",
    "role:remove",
    "role:assign_role",
    "content:read",
    "content:create",
    "content:edit",
    "content:delete",
    "content:submit_for_approval",
    "content:approve",
    "content:publish",
    "content:archive",
    "sharing:read",
    "sharing:write",
    "personal:flashcards",
    "personal:quizzes",
    "personal:ai",
    "personal:progress",
  ],
  creator: [
    "settings:read",
    "settings:write",
    "role:read",
    "role:invite",
    "role:remove",
    "role:assign_role",
    "content:read",
    "content:create",
    "content:edit",
    "content:delete",
    "content:submit_for_approval",
    "content:approve",
    "content:publish",
    "content:archive",
    "sharing:read",
    "sharing:write",
    "personal:flashcards",
    "personal:quizzes",
    "personal:ai",
    "personal:progress",
  ],
  moderator: [
    "settings:read",
    "content:read",
    "content:approve",
    "content:archive",
    "sharing:read",
    "personal:flashcards",
    "personal:quizzes",
    "personal:ai",
    "personal:progress",
  ],
  student: [
    "content:read",
    "personal:flashcards",
    "personal:quizzes",
    "personal:ai",
    "personal:progress",
  ],
};

export const ROLE_PRIORITY: PlatformRole[] = [
  "super_admin",
  "creator",
  "moderator",
  "student",
];

export interface IToken extends Document {
  accessToken: string;
  refreshToken: string;
  date: Date;
  userId: Types.ObjectId;
}

// ---------------------------------------------------------------------------
// Notification settings — embedded in IUser
// ---------------------------------------------------------------------------

/** Per-channel delivery switches for a single notification category. */
export interface INotificationChannels {
  email: boolean;
  inApp: boolean;
  push: boolean;
}

/**
 * User-controlled notification preferences.
 *
 * Toggleable categories — user can enable/disable per channel.
 * System categories — always sent; the flags are informational only.
 */
export interface INotificationSettings {
  // --- User-toggleable ---
  examReminders: INotificationChannels & {
    /** Days before the exam to send a reminder. User may pick multiple. Default [3, 1]. */
    reminderIntervals: Array<7 | 3 | 1>;
  };
  quizAvailability: INotificationChannels;
  studyPartnerActivity: INotificationChannels;
  courseAnnouncements: INotificationChannels;
  recommendationUpdates: INotificationChannels;
  /** Relevant for staff/admin roles — approval workflow events. */
  approvalStatusChanges: INotificationChannels;
  newsletter: INotificationChannels;

  // --- System / non-negotiable (user cannot disable) ---
  securityAlerts: INotificationChannels;
  accountActivity: INotificationChannels;
  systemUpdates: INotificationChannels;

  // --- Weekly study digest (opt-in) ---
  weeklyDigest: boolean;
}

export interface IOnboardingSteps {
  profile: boolean;
  yearOfStudy: boolean;
  pushOptIn: boolean;
  zIntro: boolean;
}

export interface IOnboarding {
  completed: boolean;
  completedAt?: Date;
  currentStep: number;
  steps: IOnboardingSteps;
}

export type StudentVerificationStatus =
  "none" | "pending" | "verified" | "lapsed" | "revoked";

export interface IStudentVerification {
  status: StudentVerificationStatus;
  studentEmail: string | null;
  verifiedAt: Date | null;
  expiresAt: Date | null;
  lastTokenSentAt: Date | null;
  abuseFlagged: boolean;
}

export interface IStreak {
  currentCount: number;
  longestStreak: number;
  lastStudyDate: Date | null;
  freezesAvailable: number;
  freezeUsedOnDate: Date | null;
  restoreUsedThisTerm: boolean;
  pausedForBreak: boolean;
}

export interface ILoyaltyDiscount {
  permanentPercentage: number; // 0 or 15 — unlocked at 90-day streak
}

export interface IDailyUsage {
  date: Date; // UTC midnight of the day these counters are for
  tutorSessions: number;
  quizGenerations: number;
  flashcardSets: number;
  mindMaps: number;
  materialUploads: number;
}

export interface IUserCredits {
  balance: number; // pay-as-you-go credit balance
  lifetimeEarned: number;
}

export type OAuthProvider = "google" | "github";

export interface ILinkedProvider {
  provider: OAuthProvider;
  providerUserId: string;
  email: string;
  linkedAt: Date;
}

export interface IUser extends Document {
  username: string;
  email: string;
  password?: string;
  authKey?: string;
  name: string;
  studentId?: string;
  bio?: string;
  role: "student" | "creator" | "moderator" | "super_admin";
  isBanned: boolean;
  /** True once the user proves ownership of `email` — set automatically for OAuth-created users, manually after a verification email for legacy accounts. */
  emailVerified: boolean;
  /** Linked OAuth identities. Same email can map to multiple providers; same provider is idempotent on `providerUserId`. */
  linkedProviders: ILinkedProvider[];
  accessType: "quiz" | "course" | "duration" | "default";
  isSubscribed: boolean;
  hasFreeAccess: boolean;
  freeAccessCount: number;
  lastLogin: Date;
  isDeleted: boolean;
  yearOfStudy?: number;
  preferredPersonaId?: Types.ObjectId;
  // --- New monetisation fields ---
  planTier: PlanTier | null;
  planDuration: PlanDuration | null;
  dailyUsage: IDailyUsage;
  credits: IUserCredits;
  referralCode: string;
  referredBy: Types.ObjectId | null;
  pendingReferralDiscount: boolean;
  studentVerification: IStudentVerification;
  streak: IStreak;
  loyaltyDiscount: ILoyaltyDiscount;
  // --- Deprecated (kept for backward compat) ---
  /** @deprecated Use credits.balance instead */
  quizCredits: number;
  /** @deprecated Use credits.balance instead */
  aiUsageStats: {
    totalCreditsUsed: number;
    creditsRemaining: number;
    lastRechargeDate: Date;
    monthlyUsage: Record<string, number>;
    questionsAsked: number;
    explanationsRequested: number;
  };
  notificationSettings?: INotificationSettings;
  /** refs to IStudentEnrolment */
  enrolments?: Types.ObjectId[];
  primaryEnrolmentId?: Types.ObjectId;
  programSubscriptions?: Types.ObjectId[];
  profilePicture?: Types.ObjectId | IUpload;
  /**
   * Foreign URL of the user's profile picture as last returned by an OAuth
   * provider (Google, GitHub). Stored separately from `profilePicture`
   * (which is a Qz upload) so a custom upload always wins. Set on OAuth
   * signup; on auto-link, set only when the user has no `profilePicture`.
   */
  oauthPicture?: string;
  passwordChangedAt?: Date;
  /** Last time we sent this user a `email:weekly_digest` job. Used by the digest handler as an idempotency guard so retries / replays within the same week don't double-send. */
  lastDigestSentAt?: Date | null;
  onboarding: IOnboarding;
}

// ---------------------------------------------------------------------------
// Notification document
//
// Index recommendations:
//   { userId: 1, read: 1 }
//   { userId: 1, type: 1 }
//   { scheduledFor: 1, fired: 1 }   ← for the scheduler sweep
// ---------------------------------------------------------------------------

export type NotificationType =
  | "exam_reminder"
  | "quiz_available"
  | "study_partner_request"
  | "study_partner_message"
  | "course_announcement"
  | "recommendation_update"
  | "approval_status_change"
  | "newsletter"
  | "security_alert"
  | "account_activity"
  | "system_update"
  | "program_offering_available"
  | "timetable_change"
  | "urgent_timetable_alert";

export interface INotification extends Document {
  userId: Types.ObjectId;
  type: NotificationType;
  /** If true the notification was triggered by a system event and cannot be suppressed by user settings. */
  isSystemNotification: boolean;
  /** Which delivery channels this notification was (or will be) sent on. */
  channels: { email: boolean; inApp: boolean; push: boolean };
  title: string;
  body: string;
  /** Flexible context payload — e.g. { courseId, examDate, quizId, contentType }. */
  metadata?: Record<string, unknown>;
  read: boolean;
  readAt?: Date;
  /** Set for scheduled notifications (e.g. exam reminders). */
  scheduledFor?: Date;
  sentAt?: Date;
  failed: boolean;
  failureReason?: string;
  createdAt: Date;
}

// ---------------------------------------------------------------------------
// Scheduled notification job — background job document
//
// Index recommendations:
//   { scheduledFor: 1, fired: 1, failed: 1 }
//   { targetUserId: 1 }
//   { referenceId: 1, referenceType: 1 }
// ---------------------------------------------------------------------------

export interface IScheduledNotificationJob extends Document {
  jobType: "exam_reminder" | "quiz_available";
  targetUserId: Types.ObjectId;
  /** The exam timetable entry _id or quiz _id this job is for. */
  referenceId: Types.ObjectId;
  referenceType: "exam" | "quiz";
  scheduledFor: Date;
  fired: boolean;
  firedAt?: Date;
  failed: boolean;
  failureReason?: string;
  createdAt: Date;
}
